### ISSUE TITLE
Change method names from query_element to get_element

### ISSUE THREAD

**Issue by srufle** [saresend/selenium-rs#17]
Python Version
https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webdriver.py

Java version
<https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/remote/RemoteWebDriver.html>

I am new to Rust, but have done some work with Selenium before. I think you are in the early stages so seems like an ok time to have a breaking name change. If there is a way of deprecating code I can leave your query methods and have them just call my new methods. Let me know what you think.

**Comment by saresend** [comment]
Hey! Yeah, its absolutely been sort of a small project to build out some functionality for a personal project, and is still super early stage, and will likely be able to support a breaking name change. However, I'm curious if you have a specific reason why you'd like this changed?

**Comment by whimboo** [comment]
Note that all major Selenium bindings actually use methods like `find_element` or `find_elements`, but not with the `get_` prefix. So in general keeping parity to allow people to switch more easily is pretty helpful.

Btw. thanks for starting a Rust binding!

**Comment by srufle** [comment]
You're correct, then I will create the correct `find` methods. I will work a little and then create a PR so we can review.

**Comment by saresend** [comment]
Yeah, absolutely! I wasn't aware if there was in fact a de facto standard for this

**Comment by saresend** [comment]
@srufle Are you still planning on making the proposed changes?

**Comment by srufle** [comment]
I am sorry I had intended on making my proposed changes then got busy at
work. I can try an do it this weekend. Let me know.

**Comment by saresend** [comment]
Nah no rush, it's just I may pick up and be a bit more active in developing this project, so I just wanted to check that I wasn't stepping on your toes. I can leave this to you if you still would like to contribute!

**Comment by srufle** [comment]
To run tests
```
# Start selenium server in one window
java -jar selenium-server-standalone-3.141.59.jar 

# Download  Chrome Driver - unpack and put on PATH
http://chromedriver.chromium.org/downloads

# Run Tests
cargo test
```
