### ISSUE TITLE
Bumping the version number

### ISSUE THREAD

**Issue by jwatt** [saresend/selenium-rs#23]
@tversteeg Thanks for [bumping the reqwest version](https://github.com/saresend/selenium-rs/commit/0850c813687996e5c20a70496f04024f653d0666). Unfortunately that does not appear to be enough to get other projects that depend on selenium-rs to update the version of reqwest that they build for selenium-rs when `cargo update` is run. Presumably this is because the version number of selenium-rs itself has not been bumped so they don't look to see if its dependencies have changed? Would you be able to bump the selenium-rs version number too?

**Comment by tversteeg** [comment]
I'm not the maintainer of this project, so even if I would do this I wouldn't be able to run `cargo publish` with the newest version. There have also been other commits in between so these should be reviewed for breaking changes.

**Comment by Marwes** [comment]
A new release would be appreciated! Tthe tests for https://github.com/mozilla/sccache doesn't build for me due to the that openssl issue that are fixed but not released.

**Comment by jwatt** [comment]
Are you able to do that, @saresend ?

**Comment by saresend** [comment]
Yep! I'll take a look this weekend

**Comment by alexkingnz** [comment]
What needs to be done to get this out the door?  I'd really like to use selenium-rs but can't until this is done.
