### ISSUE TITLE
How to change `query_element` to `find_element`?

### ISSUE THREAD

**Issue by joelparkerhenderson** [saresend/selenium-rs#29]
The function `query_element` succeeds but `find_element` fails as missing. 

Is there a mismatch between the documentation and the cargo crate selenium-rs? 

If so, can you please update the cargo crate, so `find_element` succeeds? Thanks!

**Comment by saresend** [comment]
Sorry I've just had a chance to get back to maintenance on these types of projects, this should now be fixed!
